name: Sync Story Status
on:
  - push
  - pull_request
  - pull_request_review
jobs:
  sync_story_status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Sync Story Status
        uses: ./
        env:
          TRACKER_API_KEY: ${{ secrets.TRACKER_API_KEY }}
